apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parlai.fullname" . }}
  labels:
    {{- include "parlai.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- required "You must provide a botConfig, see https://github.com/facebookresearch/ParlAI/blob/main/parlai/chat_service/tasks/chatbot/config.yml" .Values.botConfig | toYaml | nindent 4 }}
