apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "parlai.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
      
status: {}